"""add users table and owner_id

Revision ID: 65142d44fd71
Revises: 55145a937f0b
Create Date: 2026-07-24 11:15:25.038976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65142d44fd71'
down_revision: Union[str, None] = '55145a937f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'urls', 'users', ['owner_id'], ['id'])
    op.drop_constraint('users_owner_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_owner_id_fkey', 'users', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_column('urls', 'owner_id')
    # ### end Alembic commands ###
